name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install PWABuilder CLI tools
        run: npm install -g @pwabuilder/cli

      - name: Generate Android Package
        run: |
          pwabuilder package --manifest https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/manifest.json --platforms android --path output

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: output/
